title: Ryan Stewart, DO
description: Green Bay, WI urogynecologist providing expert care for pelvic conditions, including incontinence and prolapse, with personalized treatment options.
theme: just-the-docs

url: ryanstewart.com
baseurl: ""

# Aux links for the upper right navigation
# aux_links:
#  "YouTube":
#    - "https://youtube.com"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

footer_content: 'Copyright &copy; 2016-2025 Ryan Stewart, DO. <br /><em>The information provided is for educational purposes only and should not be considered medical advice. Always consult with a qualified healthcare professional for personalized medical guidance.</em>'

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: rslight

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Plugins
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

# Google Analytics
ga_tracking: G-1LYFEX7C2D
ga_tracking_anonymize_ip: true